#!/usr/bin/env python3
# ==============================================================================
# slack_notifier.py - Terraform Drift Alert & Slack Webhook Dispatcher
# ==============================================================================
# Parses Terraform plan JSON output, extracts attribute-level drift differences,
# constructs a Slack Block Kit payload, and sends alerts to a webhook endpoint.
# ==============================================================================

import argparse
import json
import os
import sys
import urllib.request
import urllib.error
from datetime import datetime, timezone

# ANSI Color codes for terminal output
CLR_RESET = "\033[0m"
CLR_BOLD = "\033[1m"
CLR_RED = "\033[1;31m"
CLR_GREEN = "\033[1;32m"
CLR_YELLOW = "\033[1;33m"
CLR_CYAN = "\033[1;36m"
CLR_GRAY = "\033[0;90m"


def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Format Terraform drift plan JSON into Slack Block Kit alerts"
    )
    parser.add_argument(
        "--plan-json",
        dest="plan_json",
        help="Path to the JSON plan file generated by 'terraform show -json'",
        default=None,
    )
    parser.add_argument(
        "--webhook-url",
        dest="webhook_url",
        help="Slack Incoming Webhook URL (or set SLACK_WEBHOOK_URL env var)",
        default=os.environ.get("SLACK_WEBHOOK_URL", ""),
    )
    parser.add_argument(
        "--output-payload",
        dest="output_payload",
        help="File path to save the generated Slack JSON payload",
        default=None,
    )
    parser.add_argument(
        "--environment",
        dest="environment",
        help="Target cloud environment name (e.g. production, staging)",
        default="production",
    )
    parser.add_argument(
        "--format",
        dest="format",
        choices=["terminal", "json", "slack", "all"],
        default="all",
        help="Output display format",
    )
    return parser.parse_args()


def load_plan_data(plan_json_path):
    """Loads plan data from file or stdin."""
    if plan_json_path and os.path.exists(plan_json_path):
        with open(plan_json_path, "r", encoding="utf-8") as f:
            return json.load(f)
    elif not sys.stdin.isatty():
        return json.load(sys.stdin)
    else:
        raise ValueError(
            "No input plan JSON provided. Pass --plan-json=<path> or pipe via stdin."
        )


def analyze_drift(plan_data):
    """Analyzes the resource_changes block in the Terraform plan JSON."""
    resource_changes = plan_data.get("resource_changes", [])
    drifted_resources = []

    for item in resource_changes:
        address = item.get("address", "unknown")
        res_type = item.get("type", "unknown")
        res_name = item.get("name", "unknown")
        change = item.get("change", {})
        actions = change.get("actions", [])

        # Filter out no-op resources (in-sync resources)
        if actions == ["no-op"]:
            continue

        action_type = "UPDATE"
        if actions == ["create"]:
            action_type = "CREATE (Missing Out-of-Band)"
        elif actions == ["delete"]:
            action_type = "DELETE (Orphaned in Cloud)"
        elif "delete" in actions and "create" in actions:
            action_type = "REPLACE"
        elif actions == ["update"]:
            action_type = "UPDATE (Attribute Drift)"

        before = change.get("before") or {}
        after = change.get("after") or {}

        attribute_diffs = []

        # Check for Security Group Rule differences
        if res_type == "aws_security_group":
            before_ingress = before.get("ingress", []) or []
            after_ingress = after.get("after", []) or after.get("ingress", []) or []

            # Compare ingress rules
            if len(before_ingress) != len(after_ingress):
                attribute_diffs.append(
                    f"Ingress Rules count changed: {len(before_ingress)} in cloud vs {len(after_ingress)} in IaC"
                )

            # Find unmanaged rules present in cloud but missing in code
            cloud_ports = [
                f"port {r.get('from_port')}-{r.get('to_port')}/{r.get('protocol')} from {r.get('cidr_blocks')}"
                for r in before_ingress
            ]
            code_ports = [
                f"port {r.get('from_port')}-{r.get('to_port')}/{r.get('protocol')} from {r.get('cidr_blocks')}"
                for r in after_ingress
            ]

            unmanaged = set(cloud_ports) - set(code_ports)
            if unmanaged:
                for rule in unmanaged:
                    attribute_diffs.append(f"🚨 Rogue Ingress Rule in Cloud: {rule}")

        # Check for Tag differences
        before_tags = before.get("tags") or {}
        after_tags = after.get("tags") or {}

        tag_changes = []
        for k, v in before_tags.items():
            if k not in after_tags:
                tag_changes.append(f"- Tag removed in IaC: {k}={v}")
            elif after_tags.get(k) != v:
                tag_changes.append(
                    f"~ Tag modified: Cloud '{k}={v}' vs IaC '{k}={after_tags.get(k)}'"
                )

        for k, v in after_tags.items():
            if k not in before_tags:
                tag_changes.append(f"+ Tag missing in Cloud: {k}={v}")

        if tag_changes:
            attribute_diffs.extend(tag_changes)

        if not attribute_diffs:
            attribute_diffs.append(
                f"Actions: {', '.join(actions)} (State differs from configuration)"
            )

        drifted_resources.append(
            {
                "address": address,
                "type": res_type,
                "name": res_name,
                "action": action_type,
                "diffs": attribute_diffs,
            }
        )

    return drifted_resources


def build_slack_block_kit(drifted_resources, environment):
    """Builds a rich Slack Block Kit payload representing the drift state."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    drift_count = len(drifted_resources)

    if drift_count > 0:
        header_text = f"🚨 Infrastructure Drift Detected ({environment.upper()})"
        color = "#E01E5A"  # Red
        summary_text = (
            f"*Attention SRE Team*: *{drift_count} resource(s)* have drifted out-of-band "
            f"from the declared Terraform configuration in *{environment}*."
        )
    else:
        header_text = f"✅ Infrastructure In-Sync ({environment.upper()})"
        color = "#2EB67D"  # Green
        summary_text = (
            f"All infrastructure resources in *{environment}* are strictly in sync with "
            f"Terraform code. Zero drift detected."
        )

    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": header_text,
                "emoji": True,
            },
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": summary_text,
            },
        },
        {
            "type": "section",
            "fields": [
                {
                    "type": "mrkdwn",
                    "text": f"*Environment:*\n`{environment}`",
                },
                {
                    "type": "mrkdwn",
                    "text": f"*Detection Time:*\n{timestamp}",
                },
                {
                    "type": "mrkdwn",
                    "text": f"*Drifted Items:*\n`{drift_count}`",
                },
                {
                    "type": "mrkdwn",
                    "text": "*Detection Engine:*\nTerraform / OpenTofu",
                },
            ],
        },
        {"type": "divider"},
    ]

    # Add detail blocks for each drifted resource
    for res in drifted_resources:
        diff_text = "\n".join(f"• {d}" for d in res["diffs"])
        res_block = {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    f"*{res['action']}*: `{res['address']}`\n"
                    f"*Resource Type*: `{res['type']}`\n"
                    f"```{diff_text}```"
                ),
            },
        }
        blocks.append(res_block)

    # Footer and runbook context
    blocks.append({"type": "divider"})
    blocks.append(
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": (
                        "🤖 *DevOps-SRE Automated Drift Monitor* | "
                        "Remediation: Run `terraform apply` or execute `./drift_detector.sh --remediate`"
                    ),
                }
            ],
        }
    )

    payload = {
        "text": f"Infrastructure Drift Alert: {drift_count} resources drifted in {environment}",
        "attachments": [
            {
                "color": color,
                "blocks": blocks,
            }
        ],
    }

    return payload


def display_terminal_alert(drifted_resources, environment):
    """Renders a formatted alert banner in the terminal."""
    drift_count = len(drifted_resources)
    print(f"\n{CLR_CYAN}{CLR_BOLD}" + "=" * 70)
    print(f"  📢 DRIFT ALERT REPORT: {environment.upper()} ENVIRONMENT")
    print("=" * 70 + f"{CLR_RESET}\n")

    if drift_count == 0:
        print(
            f"  {CLR_GREEN}{CLR_BOLD}✅ ZERO DRIFT DETECTED:{CLR_RESET} All cloud resources match Terraform definitions."
        )
        print("=" * 70 + "\n")
        return

    print(
        f"  {CLR_RED}{CLR_BOLD}🔴 DRIFT DETECTED!{CLR_RESET} {drift_count} cloud resource(s) diverged from code:\n"
    )

    for idx, res in enumerate(drifted_resources, 1):
        print(
            f"  [{idx}] {CLR_YELLOW}{res['action']}{CLR_RESET}: {CLR_BOLD}{res['address']}{CLR_RESET}"
        )
        print(f"      Type: {CLR_GRAY}{res['type']}{CLR_RESET}")
        for diff in res["diffs"]:
            print(f"      {CLR_RED}↳ {diff}{CLR_RESET}")
        print()

    print("=" * 70)


def send_slack_webhook(webhook_url, payload):
    """Sends the Slack payload to the webhook endpoint."""
    if not webhook_url:
        print(
            f"  {CLR_GRAY}ℹ️  No SLACK_WEBHOOK_URL configured. Skipping remote webhook dispatch.{CLR_RESET}"
        )
        return False

    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        webhook_url,
        data=data,
        headers={"Content-Type": "application/json"},
    )

    try:
        with urllib.request.urlopen(req, timeout=10) as response:
            if response.status == 200:
                print(
                    f"  {CLR_GREEN}✅ Slack alert successfully posted to webhook!{CLR_RESET}"
                )
                return True
            else:
                print(
                    f"  {CLR_YELLOW}⚠️ Webhook returned status code: {response.status}{CLR_RESET}"
                )
                return False
    except urllib.error.URLError as e:
        print(f"  {CLR_RED}❌ Failed to send Slack alert: {e}{CLR_RESET}")
        return False


def main():
    args = parse_arguments()

    try:
        plan_data = load_plan_data(args.plan_json)
    except Exception as e:
        print(f"{CLR_RED}Error loading plan JSON: {e}{CLR_RESET}", file=sys.stderr)
        sys.exit(1)

    drifted_resources = analyze_drift(plan_data)
    payload = build_slack_block_kit(drifted_resources, args.environment)

    # Save payload to file if specified
    if args.output_payload:
        os.makedirs(os.path.dirname(os.path.abspath(args.output_payload)), exist_ok=True)
        with open(args.output_payload, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2)
        print(
            f"  {CLR_GREEN}💾 Saved Slack Block Kit payload to:{CLR_RESET} {args.output_payload}"
        )

    # Display terminal representation
    if args.format in ["terminal", "all"]:
        display_terminal_alert(drifted_resources, args.environment)

    # Output raw JSON if requested
    if args.format == "json":
        print(json.dumps(payload, indent=2))

    # Send webhook if configured
    if args.webhook_url:
        send_slack_webhook(args.webhook_url, payload)

    # Return exit code based on drift presence: 0 = in sync, 2 = drifted
    if drifted_resources:
        sys.exit(2)
    else:
        sys.exit(0)


if __name__ == "__main__":
    main()
