# WireGuard Configuration - Gateway B (Site B)
# Local LAN Subnet: 10.20.0.0/24
# Tunnel Address:   10.0.0.2/24
# Listen Port:      51820

[Interface]
Address = 10.0.0.2/24
ListenPort = 51820
PrivateKey = OJf5BM4KXlZwRLzu9rDI4u84FOniEwk+9PdlkT6yeGw=

# Peer: Gateway A (Site A)
[Peer]
PublicKey = Rx/VcdTkXGHT1YY04t0aDcDL2/809jHllDWEQ9hSDEQ=
Endpoint = gateway-a:51820
AllowedIPs = 10.0.0.1/32, 10.10.0.0/24
PersistentKeepalive = 25

# Peer: Gateway C (Site C)
[Peer]
PublicKey = TLlknGf6Mns0YDZgL6PYDPFXIM6PUDwWL+qG2+D0myc=
Endpoint = gateway-c:51820
AllowedIPs = 10.0.0.3/32, 10.30.0.0/24
PersistentKeepalive = 25
