apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-
namespace: prod-environment

labels:
  - pairs:
      environment: production
      tier: live

resources:
  - ../../base
  - pdb.yaml

replicas:
  - name: payment-service
    count: 5

images:
  - name: payment-service
    newName: payment-service
    newTag: v1.4.2

configMapGenerator:
  - name: payment-config
    behavior: replace
    envs:
      - config/prod.properties

secretGenerator:
  - name: payment-secrets
    envs:
      - config/secret.env

patches:
  - path: deployment-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: payment-service
    path: json6902-patch.yaml
