apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payment-service-pdb
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/component: backend
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: payment-service
