# ==============================================================================
# Prometheus Server Container Image with SRE Multi-Burn-Rate Rules
# ==============================================================================
FROM prom/prometheus:v2.54.1

LABEL maintainer="DevOps & SRE Mini Projects"
LABEL description="Prometheus server configured with Google SRE Multiwindow Multi-Burn-Rate Alerting rules"

COPY prometheus.yml /etc/prometheus/prometheus.yml
COPY rules /etc/prometheus/rules

WORKDIR /prometheus
VOLUME [ "/prometheus" ]
EXPOSE 9090
