apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: kubernetes.io/basic-auth
stringData:
  username: app_user
  password: SecureAppPass2026!
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: default
type: Opaque
stringData:
  ACCESS_KEY_ID: minioadmin
  SECRET_ACCESS_KEY: minioadmin
