apiVersion: v1
kind: Service
metadata:
  name: autoscale-service
  namespace: hpa-demo
  labels:
    app.kubernetes.io/name: autoscale-service
    app.kubernetes.io/part-of: devops-sre-mini-projects
    app: autoscale-app
spec:
  type: ClusterIP
  selector:
    app: autoscale-app
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
