apiVersion: v1
kind: Namespace
metadata:
  name: stateless-app-demo
  labels:
    app.kubernetes.io/name: stateless-app
    app.kubernetes.io/part-of: devops-sre-mini-projects
    app.kubernetes.io/component: backend
    environment: demo
