apiVersion: v1
kind: Pod
metadata:
  name: non-compliant-privileged-pod
  labels:
    app: security-demo
    tier: insecure
spec:
  # Insecure pod violating PSA restricted profile (runs as root, privileged container, host network)
  hostNetwork: true
  containers:
    - name: root-attacker
      image: alpine:3.21
      command: ["/bin/sh", "-c", "echo 'I should be blocked!'"]
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
        runAsUser: 0
  restartPolicy: Never
