FROM nginx:alpine

LABEL maintainer="DevOps & SRE Mini Projects"
LABEL description="Nginx Reverse Proxy with Traffic Mirroring"

# Remove default nginx configurations
RUN rm -rf /etc/nginx/conf.d/* /etc/nginx/nginx.conf

# Copy custom Nginx configuration and Web Dashboard UI
COPY config/nginx.conf /etc/nginx/nginx.conf
COPY web/index.html /usr/share/nginx/html/index.html

EXPOSE 8080

HEALTHCHECK --interval=3s --timeout=2s --retries=5 \
    CMD wget -q -O- http://127.0.0.1:8080/health || exit 1

CMD ["nginx", "-g", "daemon off;"]
