apiVersion: v1
kind: Namespace
metadata:
  name: gateway-infra
  labels:
    app.kubernetes.io/part-of: gateway-api
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-apps
  labels:
    environment: production
    traffic.gateway.k8s.io/route-enabled: "true"
    pod-security.kubernetes.io/enforce: baseline
