apiVersion: v1
kind: LimitRange
metadata:
  name: prod-limit-range
  namespace: prod-critical
spec:
  limits:
    - type: Container
      default:
        cpu: 100m
        memory: 128Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: 500m
        memory: 512Mi
      min:
        cpu: 10m
        memory: 16Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: batch-limit-range
  namespace: batch-jobs
spec:
  limits:
    - type: Container
      default:
        cpu: 100m
        memory: 64Mi
      defaultRequest:
        cpu: 25m
        memory: 32Mi
      max:
        cpu: 250m
        memory: 128Mi
      min:
        cpu: 10m
        memory: 16Mi
