apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: mesh-secure
  labels:
    app: frontend
    role: client
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: mesh-secure
  labels:
    app: backend
    role: payment-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rogue-sa
  namespace: mesh-unmanaged
  labels:
    app: rogue-attacker
    role: attacker
