apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "enterprise-app.fullname" . }}-config
  labels:
    {{- include "enterprise-app.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.config.appName | quote }}
  ENVIRONMENT: {{ .Values.config.environment | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | default "INFO" | quote }}
  FEATURE_FLAGS: {{ .Values.config.featureFlags | quote }}
