apiVersion: v1
kind: Secret
metadata:
  name: {{ include "enterprise-app.fullname" . }}-secret
  labels:
    {{- include "enterprise-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.secrets.apiKey | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
