# ==============================================================================
# Grafana k6 Load Test Runner Container
# ==============================================================================
FROM grafana/k6:0.53.0

WORKDIR /scripts

COPY scripts /scripts

ENTRYPOINT ["k6"]
