apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-green
  labels:
    app: order-service
    color: green
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
      color: green
  template:
    metadata:
      labels:
        app: order-service
        color: green
    spec:
      containers:
        - name: order-service
          image: order-service:v2.0.0
          ports:
            - containerPort: 3000
          env:
            - name: APP_COLOR
              value: "green"
            - name: APP_VERSION
              value: "v2.0.0"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
