apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: config-reloading-demo
  labels:
    app.kubernetes.io/name: config-reloading-app
    app.kubernetes.io/part-of: devops-sre-mini-projects
type: Opaque
stringData:
  # Sensitive environment variables
  API_KEY: "example_dummy_api_key_secret_value_12345"
  DB_PASSWORD: "SuperSecretProductionDatabasePassword123!"

  # Sensitive secret file for volume mounting
  jwt-signing.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEA0Z5Y7d0oM+Xw8W9Kj8Fz3X3vF+1qL2mK4nP7vR8sT9uV1wX2
    yZ3aB4cD5eF6gH7iJ8kL9mN0oP1qR2sT3uV4wX5yZ6aB7cD8eF9gH0iJ1kL2mN3o
    P4qR5sT6uV7wX8yZ9aB0cD1eF2gH3iJ4kL5mN6oP7qR8sT9uV0wX1yZ2aB3cD4eF
    -----END RSA PRIVATE KEY-----
