# WireGuard Configuration - Gateway C (Site C)
# Local LAN Subnet: 10.30.0.0/24
# Tunnel Address:   10.0.0.3/24
# Listen Port:      51820

[Interface]
Address = 10.0.0.3/24
ListenPort = 51820
PrivateKey = yHeobw9QGf7cj8/YpO9kyyQoUAclB/aucHrRN7jgOnE=

# Peer: Gateway A (Site A)
[Peer]
PublicKey = Rx/VcdTkXGHT1YY04t0aDcDL2/809jHllDWEQ9hSDEQ=
Endpoint = gateway-a:51820
AllowedIPs = 10.0.0.1/32, 10.10.0.0/24
PersistentKeepalive = 25

# Peer: Gateway B (Site B)
[Peer]
PublicKey = aoYPrJ8Cgmpabl1dKBZUXPaa/iYXccihkCh+euhOwDQ=
Endpoint = gateway-b:51820
AllowedIPs = 10.0.0.2/32, 10.20.0.0/24
PersistentKeepalive = 25
