apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: monitored-app-podmonitor
  namespace: production-apps
  labels:
    app.kubernetes.io/name: monitored-app
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: monitored-app
  podMetricsEndpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
