apiVersion: v1
kind: Namespace
metadata:
  name: tenant-frontend
  labels:
    tenant: zero-trust
    tier: frontend
    network-isolation: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-backend
  labels:
    tenant: zero-trust
    tier: backend
    network-isolation: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-database
  labels:
    tenant: zero-trust
    tier: database
    network-isolation: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-untrusted
  labels:
    tenant: untrusted
    tier: attacker
    network-isolation: enabled
