#!/usr/bin/env python3
"""
sbom_analyzer.py - Software Bill of Materials (SBOM) Inspector and Compliance Engine.

Parses SPDX 2.3 and CycloneDX 1.5 JSON documents generated by Syft, categorizes
components (OS packages vs application libraries), audits open-source licenses,
and generates human-readable terminal scorecards and Markdown summaries.
"""

import os
import sys
import json
import argparse
from typing import Dict, List, Any, Optional

# ANSI Colors for Rich Console Output
CLR_RESET = "\033[0m"
CLR_BOLD = "\033[1m"
CLR_GREEN = "\033[1;32m"
CLR_RED = "\033[1;31m"
CLR_YELLOW = "\033[1;33m"
CLR_CYAN = "\033[1;36m"
CLR_MAGENTA = "\033[1;35m"
CLR_GRAY = "\033[0;90m"

PERMISSIVE_LICENSES = {
    "MIT", "Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "ISC", "Python-2.0",
    "PSF-2.0", "Unlicense", "CC0-1.0", "Zlib"
}

COPYLEFT_LICENSES = {
    "GPL-2.0", "GPL-3.0", "GPL-2.0-only", "GPL-3.0-only", "LGPL-2.1",
    "LGPL-3.0", "AGPL-3.0", "MPL-2.0"
}


def load_sbom_data(file_path: str) -> Dict[str, Any]:
    """Loads and validates JSON SBOM content from file path."""
    if not os.path.exists(file_path):
        print(f"{CLR_RED}Error: SBOM file not found at '{file_path}'{CLR_RESET}")
        sys.exit(1)
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        print(f"{CLR_RED}Error parsing JSON SBOM: {e}{CLR_RESET}")
        sys.exit(1)


def parse_spdx(data: Dict[str, Any]) -> List[Dict[str, str]]:
    """Extracts package inventory and licenses from SPDX 2.3 JSON."""
    packages = []
    for pkg in data.get("packages", []):
        name = pkg.get("name", "unknown")
        version = pkg.get("versionInfo", "unknown")
        license_concluded = pkg.get("licenseConcluded", "NOASSERTION")
        license_declared = pkg.get("licenseDeclared", "NOASSERTION")
        license_val = license_concluded if license_concluded != "NOASSERTION" else license_declared
        
        # Determine package type from externalRefs or supplier
        pkg_type = "OS/Binary"
        for ref in pkg.get("externalRefs", []):
            ref_locator = ref.get("referenceLocator", "")
            if "pkg:pypi" in ref_locator:
                pkg_type = "Python (PyPI)"
            elif "pkg:apk" in ref_locator:
                pkg_type = "Alpine (APK)"
            elif "pkg:deb" in ref_locator:
                pkg_type = "Debian (DPKG)"
            elif "pkg:rpm" in ref_locator:
                pkg_type = "RedHat (RPM)"
            elif "pkg:golang" in ref_locator:
                pkg_type = "Golang"
            elif "pkg:npm" in ref_locator:
                pkg_type = "Node (NPM)"

        packages.append({
            "name": name,
            "version": version,
            "license": license_val if license_val != "NOASSERTION" else "Not Specified",
            "type": pkg_type
        })
    return packages


def parse_cyclonedx(data: Dict[str, Any]) -> List[Dict[str, str]]:
    """Extracts package inventory and licenses from CycloneDX 1.5 JSON."""
    packages = []
    for comp in data.get("components", []):
        name = comp.get("name", "unknown")
        version = comp.get("version", "unknown")
        pkg_type_raw = comp.get("type", "library")
        purl = comp.get("purl", "")

        pkg_type = "Application Library"
        if "pkg:pypi" in purl:
            pkg_type = "Python (PyPI)"
        elif "pkg:apk" in purl:
            pkg_type = "Alpine (APK)"
        elif "pkg:deb" in purl:
            pkg_type = "Debian (DPKG)"
        elif "pkg:rpm" in purl:
            pkg_type = "RedHat (RPM)"
        elif pkg_type_raw == "operating-system":
            pkg_type = "OS Base"

        # License parsing
        licenses_list = comp.get("licenses", [])
        lic_names = []
        for item in licenses_list:
            if "license" in item:
                lic_names.append(item["license"].get("id") or item["license"].get("name") or "Unknown")
            elif "expression" in item:
                lic_names.append(item["expression"])

        license_val = ", ".join(lic_names) if lic_names else "Not Specified"

        packages.append({
            "name": name,
            "version": version,
            "license": license_val,
            "type": pkg_type
        })
    return packages


def audit_licenses(packages: List[Dict[str, str]]) -> Dict[str, Any]:
    """Audits software licenses across discovered packages."""
    permissive = 0
    copyleft = 0
    unspecified = 0
    other = 0

    type_breakdown: Dict[str, int] = {}
    license_distribution: Dict[str, int] = {}

    for pkg in packages:
        # Type breakdown
        ptype = pkg["type"]
        type_breakdown[ptype] = type_breakdown.get(ptype, 0) + 1

        # License audit
        lic = pkg["license"]
        license_distribution[lic] = license_distribution.get(lic, 0) + 1

        if lic == "Not Specified" or lic == "NOASSERTION":
            unspecified += 1
        elif any(perm.lower() in lic.lower() for perm in PERMISSIVE_LICENSES):
            permissive += 1
        elif any(copy.lower() in lic.lower() for copy in COPYLEFT_LICENSES):
            copyleft += 1
        else:
            other += 1

    return {
        "total": len(packages),
        "permissive": permissive,
        "copyleft": copyleft,
        "unspecified": unspecified,
        "other": other,
        "type_breakdown": type_breakdown,
        "license_distribution": license_distribution
    }


def render_terminal_scorecard(sbom_path: str, packages: List[Dict[str, str]], audit: Dict[str, Any]):
    """Renders formatted ANSI dashboard in the terminal."""
    print(f"\n{CLR_CYAN}{CLR_BOLD}======================================================================")
    print("  📋 SOFTWARE BILL OF MATERIALS (SBOM) COMPLIANCE SCORECARD")
    print(f"======================================================================{CLR_RESET}")
    print(f" Source File       : {CLR_GRAY}{sbom_path}{CLR_RESET}")
    print(f" Total Components  : {CLR_BOLD}{audit['total']}{CLR_RESET} cataloged packages")
    print(f" Permissive Lic    : {CLR_GREEN}{audit['permissive']}{CLR_RESET} (MIT, Apache-2.0, BSD, etc.)")
    print(f" Copyleft Lic      : {CLR_YELLOW}{audit['copyleft']}{CLR_RESET} (GPL, LGPL, MPL, etc.)")
    print(f" Unspecified Lic   : {CLR_GRAY}{audit['unspecified']}{CLR_RESET}")
    print(f"======================================================================")

    print(f"\n{CLR_BOLD}📦 Package Type Distribution:{CLR_RESET}")
    for ptype, count in sorted(audit["type_breakdown"].items(), key=lambda x: x[1], reverse=True):
        print(f"  • {ptype:<20} : {CLR_CYAN}{count:>3}{CLR_RESET} packages")

    print(f"\n{CLR_BOLD}📜 Component Sample Inventory (First 12 items):{CLR_RESET}")
    print(f"  {'Package Name':<28} {'Version':<18} {'Type':<18} {'License':<15}")
    print(f"  {'-'*28} {'-'*18} {'-'*18} {'-'*15}")

    for pkg in packages[:12]:
        name = pkg['name'][:26]
        ver = pkg['version'][:16]
        ptype = pkg['type'][:16]
        lic = pkg['license'][:15]
        print(f"  {name:<28} {ver:<18} {ptype:<18} {CLR_GRAY}{lic:<15}{CLR_RESET}")

    if len(packages) > 12:
        print(f"  ... and {len(packages) - 12} additional components listed in SBOM report.")
    print(f"======================================================================\n")


def generate_markdown_report(output_path: str, sbom_path: str, packages: List[Dict[str, str]], audit: Dict[str, Any]):
    """Generates executive markdown summary file for audit logging."""
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    
    rows = []
    for pkg in packages:
        rows.append(f"| `{pkg['name']}` | `{pkg['version']}` | {pkg['type']} | {pkg['license']} |")
    package_table = "\n".join(rows)

    type_rows = []
    for ptype, count in sorted(audit["type_breakdown"].items(), key=lambda x: x[1], reverse=True):
        type_rows.append(f"| **{ptype}** | {count} |")
    type_table = "\n".join(type_rows)

    content = f"""# Software Bill of Materials (SBOM) Compliance Report

Generated automatically by `sbom_analyzer.py` during container supply chain verification.

## 📊 Summary Metrics

| Metric | Count | Assessment |
| :--- | :--- | :--- |
| **Total Cataloged Packages** | **{audit['total']}** | Inventory Complete |
| **Permissive Open Source** | **{audit['permissive']}** | ✅ Low Risk (Approved) |
| **Copyleft / Restrictive** | **{audit['copyleft']}** | ⚠️ Review Required |
| **Unspecified / Proprietary** | **{audit['unspecified']}** | ℹ️ Notice |

## 📦 Package Classification

| Ecosystem / Category | Component Count |
| :--- | :--- |
{type_table}

## 📋 Complete Software Component Inventory

| Component Name | Version | Ecosystem | License |
| :--- | :--- | :--- | :--- |
{package_table}

---
*Report generated from `{os.path.basename(sbom_path)}` via Anchore Syft & Sigstore Cosign.*
"""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  [{CLR_GREEN}SAVED{CLR_RESET}] Executive SBOM Markdown summary written to: {CLR_GRAY}{output_path}{CLR_RESET}")


def main():
    parser = argparse.ArgumentParser(description="Software Bill of Materials (SBOM) Inspector and Compliance Analyzer.")
    parser.add_argument("--file", "-f", default="reports/sbom.spdx.json", help="Path to SPDX or CycloneDX JSON file.")
    parser.add_argument("--output-md", "-o", default="reports/sbom_analysis.md", help="Path for generated Markdown summary.")
    args = parser.parse_args()

    raw_data = load_sbom_data(args.file)

    # Detect SBOM format
    if "spdxVersion" in raw_data or "packages" in raw_data:
        packages = parse_spdx(raw_data)
    elif "bomFormat" in raw_data or "components" in raw_data:
        packages = parse_cyclonedx(raw_data)
    else:
        # Fallback to SPDX parser
        packages = parse_spdx(raw_data)

    audit = audit_licenses(packages)
    render_terminal_scorecard(args.file, packages, audit)
    generate_markdown_report(args.output_md, args.file, packages, audit)


if __name__ == "__main__":
    main()
