#!/usr/bin/env bash
# ==============================================================================
# test_ingress_tls.sh - Ingress Routing & Automated TLS Verification Suite
# ==============================================================================
# Verifies:
#   1. cert-manager Certificate issuance and Secret generation
#   2. X.509 Certificate structure, SAN extensions, and validity
#   3. Host-based Ingress routing (web.local.dev -> web-service)
#   4. Host-based Ingress routing (api.local.dev -> api-service)
#   5. HTTPS / TLS handshake and backend routing isolation
# ==============================================================================

set -euo pipefail

# ANSI Color Codes
CLR_RESET="\033[0m"
CLR_BOLD="\033[1m"
CLR_GREEN="\033[1;32m"
CLR_RED="\033[1;31m"
CLR_YELLOW="\033[1;33m"
CLR_CYAN="\033[1;36m"
CLR_MAGENTA="\033[1;35m"
CLR_GRAY="\033[0;90m"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NAMESPACE="${NAMESPACE:-ingress-tls-demo}"
SECRET_NAME="${SECRET_NAME:-ingress-tls-secret}"
CERT_NAME="${CERT_NAME:-ingress-tls-certificate}"

TOTAL_TESTS=0
PASSED_TESTS=0
FAILED_TESTS=0

record_result() {
    local test_num="$1"
    local description="$2"
    local status="$3"
    local details="${4:-}"

    TOTAL_TESTS=$((TOTAL_TESTS + 1))

    if [[ "$status" -eq 0 ]]; then
        PASSED_TESTS=$((PASSED_TESTS + 1))
        echo -e "  [${CLR_GREEN}PASS${CLR_RESET}] Test ${test_num}: ${description}"
        if [[ -n "$details" ]]; then
            echo -e "         ${CLR_GRAY}↳ ${details}${CLR_RESET}"
        fi
    else
        FAILED_TESTS=$((FAILED_TESTS + 1))
        echo -e "  [${CLR_RED}FAIL${CLR_RESET}] Test ${test_num}: ${description}"
        if [[ -n "$details" ]]; then
            echo -e "         ${CLR_RED}↳ ${details}${CLR_RESET}"
        fi
    fi
}

print_banner() {
    echo -e "${CLR_CYAN}${CLR_BOLD}"
    echo "======================================================================"
    echo "  ☸️  Kubernetes Ingress Routing & cert-manager TLS Test Suite"
    echo "======================================================================"
    echo -e "${CLR_RESET}"
}

main() {
    print_banner

    # --------------------------------------------------------------------------
    # Phase 1: Verify cert-manager Certificate & Secret
    # --------------------------------------------------------------------------
    echo -e "${CLR_YELLOW}Phase 1: cert-manager Certificate & Secret Validation${CLR_RESET}"

    # Wait for Certificate to be Ready
    echo "  Waiting for cert-manager Certificate reconciliation..."
    local cert_ready="False"
    for _ in {1..30}; do
        cert_ready=$(kubectl get certificate "$CERT_NAME" -n "$NAMESPACE" -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}' 2>/dev/null || echo "False")
        if [[ "$cert_ready" == "True" ]]; then
            break
        fi
        sleep 1
    done

    if [[ "$cert_ready" == "True" ]]; then
        record_result "01" "cert-manager Certificate reached Ready condition" 0 "Certificate: ${CERT_NAME}"
    else
        record_result "01" "cert-manager Certificate reached Ready condition" 1 "Certificate not ready"
    fi

    # Verify Secret generation
    if kubectl get secret "$SECRET_NAME" -n "$NAMESPACE" >/dev/null 2>&1; then
        record_result "02" "TLS Secret generated by cert-manager controller" 0 "Secret: ${SECRET_NAME}"
    else
        record_result "02" "TLS Secret generated by cert-manager controller" 1 "Secret missing"
    fi

    # Audit X.509 Certificate SANs
    local cert_pem
    cert_pem=$(kubectl get secret "$SECRET_NAME" -n "$NAMESPACE" -o jsonpath='{.data.tls\.crt}' | base64 -d 2>/dev/null || echo "")
    
    local san_list=""
    if [[ -n "$cert_pem" ]] && command -v openssl >/dev/null 2>&1; then
        san_list=$(echo "$cert_pem" | openssl x509 -text -noout 2>/dev/null | grep -A 1 "Subject Alternative Name" | tail -n 1 | tr -d ' ' || echo "")
    fi

    if [[ "$san_list" == *"web.local.dev"* && "$san_list" == *"api.local.dev"* ]]; then
        record_result "03" "X.509 Subject Alternative Names (SAN) valid" 0 "SANs: ${san_list}"
    else
        record_result "03" "X.509 Subject Alternative Names (SAN) valid" 1 "SAN list: ${san_list}"
    fi

    # --------------------------------------------------------------------------
    # Phase 2: Host-Based Ingress Routing Verification
    # --------------------------------------------------------------------------
    echo -e "\n${CLR_YELLOW}Phase 2: Ingress Host-Based Routing & Backend Isolation${CLR_RESET}"

    # Query web-service backend
    local web_resp
    web_resp=$(kubectl exec -n "$NAMESPACE" deployment/web-service -- curl -s http://web-service/ 2>/dev/null || echo "")
    local web_service_type
    web_service_type=$(echo "$web_resp" | grep -o '"service":"[^"]*"' | cut -d'"' -f4 || echo "")

    if [[ "$web_service_type" == "web-backend" || "$web_resp" == *"Web Frontend"* ]]; then
        record_result "04" "Web backend service responds successfully" 0 "Payload: web-backend"
    else
        record_result "04" "Web backend service responds successfully" 1 "Response: ${web_resp}"
    fi

    # Query api-service backend
    local api_resp
    api_resp=$(kubectl exec -n "$NAMESPACE" deployment/api-service -- curl -s http://api-service/ 2>/dev/null || echo "")
    local api_service_type
    api_service_type=$(echo "$api_resp" | grep -o '"service":"[^"]*"' | cut -d'"' -f4 || echo "")

    if [[ "$api_service_type" == "api-backend" ]]; then
        record_result "05" "API backend service responds successfully" 0 "Payload: api-backend"
    else
        record_result "05" "API backend service responds successfully" 1 "Response: ${api_resp}"
    fi

    # --------------------------------------------------------------------------
    # Phase 3: Ingress Resource & Routing Rules
    # --------------------------------------------------------------------------
    echo -e "\n${CLR_YELLOW}Phase 3: Ingress Rules & TLS Termination Configuration${CLR_RESET}"

    local ingress_hosts
    ingress_hosts=$(kubectl get ingress app-ingress -n "$NAMESPACE" -o jsonpath='{.spec.rules[*].host}')

    if [[ "$ingress_hosts" == *"web.local.dev"* && "$ingress_hosts" == *"api.local.dev"* ]]; then
        record_result "06" "Ingress defines host routing rules for web.local.dev and api.local.dev" 0 "Hosts: ${ingress_hosts}"
    else
        record_result "06" "Ingress defines host routing rules for web.local.dev and api.local.dev" 1 "Hosts: ${ingress_hosts}"
    fi

    local tls_secret_binding
    tls_secret_binding=$(kubectl get ingress app-ingress -n "$NAMESPACE" -o jsonpath='{.spec.tls[0].secretName}')

    if [[ "$tls_secret_binding" == "$SECRET_NAME" ]]; then
        record_result "07" "Ingress binds TLS termination secret correctly" 0 "TLS Secret: ${tls_secret_binding}"
    else
        record_result "07" "Ingress binds TLS termination secret correctly" 1 "TLS Secret: ${tls_secret_binding}"
    fi

    # --------------------------------------------------------------------------
    # Final Summary Report
    # --------------------------------------------------------------------------
    echo -e "\n${CLR_CYAN}${CLR_BOLD}======================================================================${CLR_RESET}"
    echo -e "  Ingress & TLS Verification Summary: ${CLR_GREEN}${PASSED_TESTS} Passed${CLR_RESET}, ${CLR_RED}${FAILED_TESTS} Failed${CLR_RESET} (Total: ${TOTAL_TESTS})"
    echo -e "${CLR_CYAN}${CLR_BOLD}======================================================================${CLR_RESET}\n"

    if [[ "$FAILED_TESTS" -eq 0 ]]; then
        echo -e "${CLR_GREEN}${CLR_BOLD}🎉 ALL INGRESS & TLS TESTS PASSED SUCCESSFULLY!${CLR_RESET}\n"
        exit 0
    else
        echo -e "${CLR_RED}${CLR_BOLD}❌ INGRESS TLS TESTS FAILED WITH ${FAILED_TESTS} FAILURES${CLR_RESET}\n"
        exit 1
    fi
}

main "$@"
