apiVersion: v1
kind: Service
metadata:
  name: stateful-service
  namespace: statefulset-demo
  labels:
    app.kubernetes.io/name: stateful-service
    app.kubernetes.io/part-of: devops-sre-mini-projects
    app: stateful-app
spec:
  clusterIP: None # Headless Service for direct pod DNS addressing
  selector:
    app: stateful-app
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
