apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-app
  namespace: statefulset-demo
  labels:
    app.kubernetes.io/name: stateful-app
    app.kubernetes.io/part-of: devops-sre-mini-projects
    app: stateful-app
spec:
  serviceName: stateful-service
  replicas: 3
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: stateful-app
  template:
    metadata:
      labels:
        app: stateful-app
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
      containers:
        - name: app
          image: stateful-app:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: DATA_DIR
              value: "/data"
            - name: HEADLESS_SERVICE
              value: "stateful-service"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
          volumeMounts:
            - name: data-volume
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 3
  volumeClaimTemplates:
    - metadata:
        name: data-volume
        labels:
          app.kubernetes.io/name: stateful-app
          app.kubernetes.io/part-of: devops-sre-mini-projects
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
