apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    app.kubernetes.io/part-of: cluster-logging
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: workload-apps
  labels:
    environment: demo
    pod-security.kubernetes.io/enforce: baseline
